package pe.edu.unsch.entity;
// Generated 05-jul-2019 9:04:46 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CargaAcademica generated by hbm2java
 */
@Entity
@Table(name = "carga_academica", catalog = "cargabd")
public class CargaAcademica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCarga;
	private Docente docente;
	private String semestreAcademico;
	private int numeroHorasSemanales;

	public CargaAcademica() {
	}

	public CargaAcademica(int idCarga, Docente docente, String semestreAcademico, int numeroHorasSemanales) {
		this.idCarga = idCarga;
		this.docente = docente;
		this.semestreAcademico = semestreAcademico;
		this.numeroHorasSemanales = numeroHorasSemanales;
	}

	@Id

	@Column(name = "id_carga", unique = true, nullable = false)
	public int getIdCarga() {
		return this.idCarga;
	}

	public void setIdCarga(int idCarga) {
		this.idCarga = idCarga;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_docente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "semestre_academico", nullable = false, length = 10)
	public String getSemestreAcademico() {
		return this.semestreAcademico;
	}

	public void setSemestreAcademico(String semestreAcademico) {
		this.semestreAcademico = semestreAcademico;
	}

	@Column(name = "numero_horas_semanales", nullable = false)
	public int getNumeroHorasSemanales() {
		return this.numeroHorasSemanales;
	}

	public void setNumeroHorasSemanales(int numeroHorasSemanales) {
		this.numeroHorasSemanales = numeroHorasSemanales;
	}

}
